-- BLOXFLIP IS FOR BABIES AND IS A FUCKING SCAM NEVER TOUCH THAT THING IN YOUR FUCKING LIFE
-- GAY BLOXFLIP NEVER TOUCH THIS SHIT, I LOST 100MILLION FUCKING ROBUX
-- NEVER TOUCH BLOXFLIP
-- WHY THE FUCK ARE YOU READING MY CODE
-- KILL YORSELF BLOXFLIP
-- KILL YOURSELF RENO
-- THIS IS SHIT
-- KILL YOURSELF
-- TNT IS THE BEST AT BLOXFLIP
-- ALWAYS TRUST TNT
-- HE KNOWS EVERYTHING
-- DONT USE PREDICTORS
-- DONT BE DUCKY
-- DUCKY IS ASS AT BLOXFLIP
-- DUCKY FAILED NNN
-- ALWAYS USE PREDICTORS THAT FAIL
-- TNT FAILED NNN
-- COLREALPRO HASNT FAILED NNN
-- HOW FAIL NNN
-- cum

--[[
    Created By ColRealPro#4927
    Please shut the fuck up about errors xd
]]